// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: api/llm/v1/llm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLlmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateLlmRequest) Reset() {
	*x = CreateLlmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLlmRequest) ProtoMessage() {}

func (x *CreateLlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLlmRequest.ProtoReflect.Descriptor instead.
func (*CreateLlmRequest) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{0}
}

type CreateLlmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateLlmReply) Reset() {
	*x = CreateLlmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLlmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLlmReply) ProtoMessage() {}

func (x *CreateLlmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLlmReply.ProtoReflect.Descriptor instead.
func (*CreateLlmReply) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{1}
}

type UpdateLlmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLlmRequest) Reset() {
	*x = UpdateLlmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLlmRequest) ProtoMessage() {}

func (x *UpdateLlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLlmRequest.ProtoReflect.Descriptor instead.
func (*UpdateLlmRequest) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{2}
}

type UpdateLlmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLlmReply) Reset() {
	*x = UpdateLlmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLlmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLlmReply) ProtoMessage() {}

func (x *UpdateLlmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLlmReply.ProtoReflect.Descriptor instead.
func (*UpdateLlmReply) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{3}
}

type DeleteLlmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteLlmRequest) Reset() {
	*x = DeleteLlmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLlmRequest) ProtoMessage() {}

func (x *DeleteLlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLlmRequest.ProtoReflect.Descriptor instead.
func (*DeleteLlmRequest) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{4}
}

type DeleteLlmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteLlmReply) Reset() {
	*x = DeleteLlmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLlmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLlmReply) ProtoMessage() {}

func (x *DeleteLlmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLlmReply.ProtoReflect.Descriptor instead.
func (*DeleteLlmReply) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{5}
}

type GetLlmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLlmRequest) Reset() {
	*x = GetLlmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLlmRequest) ProtoMessage() {}

func (x *GetLlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLlmRequest.ProtoReflect.Descriptor instead.
func (*GetLlmRequest) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{6}
}

type GetLlmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLlmReply) Reset() {
	*x = GetLlmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLlmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLlmReply) ProtoMessage() {}

func (x *GetLlmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLlmReply.ProtoReflect.Descriptor instead.
func (*GetLlmReply) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{7}
}

type ListLlmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLlmRequest) Reset() {
	*x = ListLlmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLlmRequest) ProtoMessage() {}

func (x *ListLlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLlmRequest.ProtoReflect.Descriptor instead.
func (*ListLlmRequest) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{8}
}

type ListLlmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLlmReply) Reset() {
	*x = ListLlmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_llm_v1_llm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLlmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLlmReply) ProtoMessage() {}

func (x *ListLlmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLlmReply.ProtoReflect.Descriptor instead.
func (*ListLlmReply) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_proto_rawDescGZIP(), []int{9}
}

var File_api_llm_v1_llm_proto protoreflect.FileDescriptor

var file_api_llm_v1_llm_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6c, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e,
	0x76, 0x31, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x6c, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x6c, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6c, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6c,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd9, 0x02, 0x0a, 0x03, 0x4c, 0x6c, 0x6d, 0x12, 0x45,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x12, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x6c, 0x6d, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6c, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6c, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c, 0x6c, 0x6d, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6c,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6c, 0x6d, 0x12, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6c,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x6c, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6c, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x25, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x15, 0x74, 0x61, 0x6f, 0x2d, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_llm_v1_llm_proto_rawDescOnce sync.Once
	file_api_llm_v1_llm_proto_rawDescData = file_api_llm_v1_llm_proto_rawDesc
)

func file_api_llm_v1_llm_proto_rawDescGZIP() []byte {
	file_api_llm_v1_llm_proto_rawDescOnce.Do(func() {
		file_api_llm_v1_llm_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_llm_v1_llm_proto_rawDescData)
	})
	return file_api_llm_v1_llm_proto_rawDescData
}

var file_api_llm_v1_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_llm_v1_llm_proto_goTypes = []interface{}{
	(*CreateLlmRequest)(nil), // 0: api.llm.v1.CreateLlmRequest
	(*CreateLlmReply)(nil),   // 1: api.llm.v1.CreateLlmReply
	(*UpdateLlmRequest)(nil), // 2: api.llm.v1.UpdateLlmRequest
	(*UpdateLlmReply)(nil),   // 3: api.llm.v1.UpdateLlmReply
	(*DeleteLlmRequest)(nil), // 4: api.llm.v1.DeleteLlmRequest
	(*DeleteLlmReply)(nil),   // 5: api.llm.v1.DeleteLlmReply
	(*GetLlmRequest)(nil),    // 6: api.llm.v1.GetLlmRequest
	(*GetLlmReply)(nil),      // 7: api.llm.v1.GetLlmReply
	(*ListLlmRequest)(nil),   // 8: api.llm.v1.ListLlmRequest
	(*ListLlmReply)(nil),     // 9: api.llm.v1.ListLlmReply
}
var file_api_llm_v1_llm_proto_depIdxs = []int32{
	0, // 0: api.llm.v1.Llm.CreateLlm:input_type -> api.llm.v1.CreateLlmRequest
	2, // 1: api.llm.v1.Llm.UpdateLlm:input_type -> api.llm.v1.UpdateLlmRequest
	4, // 2: api.llm.v1.Llm.DeleteLlm:input_type -> api.llm.v1.DeleteLlmRequest
	6, // 3: api.llm.v1.Llm.GetLlm:input_type -> api.llm.v1.GetLlmRequest
	8, // 4: api.llm.v1.Llm.ListLlm:input_type -> api.llm.v1.ListLlmRequest
	1, // 5: api.llm.v1.Llm.CreateLlm:output_type -> api.llm.v1.CreateLlmReply
	3, // 6: api.llm.v1.Llm.UpdateLlm:output_type -> api.llm.v1.UpdateLlmReply
	5, // 7: api.llm.v1.Llm.DeleteLlm:output_type -> api.llm.v1.DeleteLlmReply
	7, // 8: api.llm.v1.Llm.GetLlm:output_type -> api.llm.v1.GetLlmReply
	9, // 9: api.llm.v1.Llm.ListLlm:output_type -> api.llm.v1.ListLlmReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_llm_v1_llm_proto_init() }
func file_api_llm_v1_llm_proto_init() {
	if File_api_llm_v1_llm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_llm_v1_llm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLlmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLlmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLlmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLlmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLlmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLlmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLlmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLlmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLlmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_llm_v1_llm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLlmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_llm_v1_llm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_llm_v1_llm_proto_goTypes,
		DependencyIndexes: file_api_llm_v1_llm_proto_depIdxs,
		MessageInfos:      file_api_llm_v1_llm_proto_msgTypes,
	}.Build()
	File_api_llm_v1_llm_proto = out.File
	file_api_llm_v1_llm_proto_rawDesc = nil
	file_api_llm_v1_llm_proto_goTypes = nil
	file_api_llm_v1_llm_proto_depIdxs = nil
}
